CREATE TABLE [dbo].[Horas] (
    [Empleado] NVARCHAR (400) NOT NULL,
    [Proyecto] NVARCHAR (400) NOT NULL,
    [Tarea]    NVARCHAR (400) NOT NULL,
    [Mes]      NVARCHAR (50)  NOT NULL,
    [D1]       INT            DEFAULT ((0)) NULL,
    [H1]       INT            DEFAULT ((0)) NULL,
    [C1]       NVARCHAR (MAX) NULL,
    [O1]       NVARCHAR (MAX) NULL,
    [D2]       INT            DEFAULT ((0)) NULL,
    [H2]       INT            DEFAULT ((0)) NULL,
    [C2]       NVARCHAR (MAX) NULL,
    [O2]       NVARCHAR (MAX) NULL,
    [D3]       INT            DEFAULT ((0)) NULL,
    [H3]       INT            DEFAULT ((0)) NULL,
    [C3]       NVARCHAR (MAX) NULL,
    [O3]       NVARCHAR (MAX) NULL,
    [D4]       INT            DEFAULT ((0)) NULL,
    [H4]       INT            DEFAULT ((0)) NULL,
    [C4]       NVARCHAR (MAX) NULL,
    [O4]       NVARCHAR (MAX) NULL,
    [D5]       INT            DEFAULT ((0)) NULL,
    [H5]       INT            DEFAULT ((0)) NULL,
    [C5]       NVARCHAR (MAX) NULL,
    [O5]       NVARCHAR (MAX) NULL,
    [D6]       INT            DEFAULT ((0)) NULL,
    [H6]       INT            DEFAULT ((0)) NULL,
    [C6]       NVARCHAR (MAX) NULL,
    [O6]       NVARCHAR (MAX) NULL,
    [D7]       INT            DEFAULT ((0)) NULL,
    [H7]       INT            DEFAULT ((0)) NULL,
    [C7]       NVARCHAR (MAX) NULL,
    [O7]       NVARCHAR (MAX) NULL,
    [D8]       INT            DEFAULT ((0)) NULL,
    [H8]       INT            DEFAULT ((0)) NULL,
    [C8]       NVARCHAR (MAX) NULL,
    [O8]       NVARCHAR (MAX) NULL,
    [D9]       INT            DEFAULT ((0)) NULL,
    [H9]       INT            DEFAULT ((0)) NULL,
    [C9]       NVARCHAR (MAX) NULL,
    [O9]       NVARCHAR (MAX) NULL,
    [D10]      INT            DEFAULT ((0)) NULL,
    [H10]      INT            DEFAULT ((0)) NULL,
    [C10]      NVARCHAR (MAX) NULL,
    [O10]      NVARCHAR (MAX) NULL,
    [D11]      INT            DEFAULT ((0)) NULL,
    [H11]      INT            DEFAULT ((0)) NULL,
    [C11]      NVARCHAR (MAX) NULL,
    [O11]      NVARCHAR (MAX) NULL,
    [D12]      INT            DEFAULT ((0)) NULL,
    [H12]      INT            DEFAULT ((0)) NULL,
    [C12]      NVARCHAR (MAX) NULL,
    [O12]      NVARCHAR (MAX) NULL,
    [D13]      INT            DEFAULT ((0)) NULL,
    [H13]      INT            DEFAULT ((0)) NULL,
    [C13]      NVARCHAR (MAX) NULL,
    [O13]      NVARCHAR (MAX) NULL,
    [D14]      INT            DEFAULT ((0)) NULL,
    [H14]      INT            DEFAULT ((0)) NULL,
    [C14]      NVARCHAR (MAX) NULL,
    [O14]      NVARCHAR (MAX) NULL,
    [D15]      INT            DEFAULT ((0)) NULL,
    [H15]      INT            DEFAULT ((0)) NULL,
    [C15]      NVARCHAR (MAX) NULL,
    [O15]      NVARCHAR (MAX) NULL,
    [D16]      INT            DEFAULT ((0)) NULL,
    [H16]      INT            DEFAULT ((0)) NULL,
    [C16]      NVARCHAR (MAX) NULL,
    [O16]      NVARCHAR (MAX) NULL,
    [D17]      INT            DEFAULT ((0)) NULL,
    [H17]      INT            DEFAULT ((0)) NULL,
    [C17]      NVARCHAR (MAX) NULL,
    [O17]      NVARCHAR (MAX) NULL,
    [D18]      INT            DEFAULT ((0)) NULL,
    [H18]      INT            DEFAULT ((0)) NULL,
    [C18]      NVARCHAR (MAX) NULL,
    [O18]      NVARCHAR (MAX) NULL,
    [D19]      INT            DEFAULT ((0)) NULL,
    [H19]      INT            DEFAULT ((0)) NULL,
    [C19]      NVARCHAR (MAX) NULL,
    [O19]      NVARCHAR (MAX) NULL,
    [D20]      INT            DEFAULT ((0)) NULL,
    [H20]      INT            DEFAULT ((0)) NULL,
    [C20]      NVARCHAR (MAX) NULL,
    [O20]      NVARCHAR (MAX) NULL,
    [D21]      INT            DEFAULT ((0)) NULL,
    [H21]      INT            DEFAULT ((0)) NULL,
    [C21]      NVARCHAR (MAX) NULL,
    [O21]      NVARCHAR (MAX) NULL,
    [D22]      INT            DEFAULT ((0)) NULL,
    [H22]      INT            DEFAULT ((0)) NULL,
    [C22]      NVARCHAR (MAX) NULL,
    [O22]      NVARCHAR (MAX) NULL,
    [D23]      INT            DEFAULT ((0)) NULL,
    [H23]      INT            DEFAULT ((0)) NULL,
    [C23]      NVARCHAR (MAX) NULL,
    [O23]      NVARCHAR (MAX) NULL,
    [D24]      INT            DEFAULT ((0)) NULL,
    [H24]      INT            DEFAULT ((0)) NULL,
    [C24]      NVARCHAR (MAX) NULL,
    [O24]      NVARCHAR (MAX) NULL,
    [D25]      INT            DEFAULT ((0)) NULL,
    [H25]      INT            DEFAULT ((0)) NULL,
    [C25]      NVARCHAR (MAX) NULL,
    [O25]      NVARCHAR (MAX) NULL,
    [D26]      INT            DEFAULT ((0)) NULL,
    [H26]      INT            DEFAULT ((0)) NULL,
    [C26]      NVARCHAR (MAX) NULL,
    [O26]      NVARCHAR (MAX) NULL,
    [D27]      INT            DEFAULT ((0)) NULL,
    [H27]      INT            DEFAULT ((0)) NULL,
    [C27]      NVARCHAR (MAX) NULL,
    [O27]      NVARCHAR (MAX) NULL,
    [D28]      INT            DEFAULT ((0)) NULL,
    [H28]      INT            DEFAULT ((0)) NULL,
    [C28]      NVARCHAR (MAX) NULL,
    [O28]      NVARCHAR (MAX) NULL,
    [D29]      INT            DEFAULT ((0)) NULL,
    [H29]      INT            DEFAULT ((0)) NULL,
    [C29]      NVARCHAR (MAX) NULL,
    [O29]      NVARCHAR (MAX) NULL,
    [D30]      INT            DEFAULT ((0)) NULL,
    [H30]      INT            DEFAULT ((0)) NULL,
    [C30]      NVARCHAR (MAX) NULL,
    [O30]      NVARCHAR (MAX) NULL,
    [D31]      INT            DEFAULT ((0)) NULL,
    [H31]      INT            DEFAULT ((0)) NULL,
    [C31]      NVARCHAR (MAX) NULL,
    [O31]      NVARCHAR (MAX) NULL,
    [Total]    INT            DEFAULT ((0)) NULL,
    CONSTRAINT [PK_Horas] PRIMARY KEY CLUSTERED ([Empleado] ASC, [Proyecto] ASC, [Tarea] ASC, [Mes] ASC)
);

